transplant code from F4 to F1
qiayuanliao/imu2can pull request #3
Opened 2022-04-02 06:39 UTC by 582864732

2022-04-03 05:17 UTC, qiayuanliao requested changes
整个项目名称叫 imu2can 就行了 没必要改成 imu2ccan_F1, 其他没问题了

2022-04-03 11:30 UTC, 582864732 commented
把imu2can_F1改名成了imu2can

2022-04-06 11:05 UTC, qiayuanliao commented
Commit的信息首字母大写

2022-04-07 13:36 UTC, qiayuanliao commented
@582864732

2022-04-11 01:23 UTC, qiayuanliao commented
@582864732

2022-04-14 14:16 UTC, qiayuanliao commented
@582864732

2022-04-16 04:40 UTC, merged